### ISSUE TITLE
use datasource gradle

### ISSUE THREAD

**Issue by duosonic62** [duosonic62/strings-history#4]
## tasks
- [ ] create datasource.gradle
- [ ] fix doma-gen.gradle(use datasource)
- [ ] fix build.gradle(use datasource)
